### ISSUE TITLE
RecreatingDB Stuck

### ISSUE THREAD

**Issue by Soullover77** [mogyiii/Alduin-botnet#3]
After opening the AlduinDBCreator.exe - A cmd window with a line ( Recreating DB ) is stuck forever. nothing happens after that. requesting assistance.

**Comment by urgheuigrpauipeg** [comment]
No idea what is wrong, i have tried everything to get this working but i just cant for some reason. Instructions are very unclear.

**Comment by mogyiii** [comment]
could you send a screenshot of it?

**Comment by Soullover77** [comment]
Hey i couldn't recreate the scenario i edited the app settings.json and the database creator gives me an error alduin doesn't exist and also when i import the sql file into postgersql it gives error code 1

**Comment by explowz** [comment]
> Hey i couldn't recreate the scenario i edited the app settings.json and the database creator gives me an error alduin doesn't exist and also when i import the sql file into postgersql it gives error code 1

Error code 1 can be ignored and is not a problem.

**Comment by mogyiii** [comment]
Create postgres database if not exist and edit DatabaseCreator appsettings.json and try run Datebasecreator

**Comment by Soullover77** [comment]
Could i contact you elsewhere? Discord maybe? I might need some assistance if you don't mind spending a few mins 

Sent from Yahoo Mail on Android 
 
  On Thu, 21 Jan 2021 at 3:05, mogyiii<notifications@github.com> wrote:   


Create postgres database if not exist and edit DatabaseCreator appsettings.json and try run Datebasecreator

**Comment by mogyiii** [comment]
My discord name is "mogyiii#9533"

**Comment by anesfane** [comment]
Hi i receive this after add email on create db, i add you on discord
Error:
NHibernate.Exceptions.GenericADOException: could not get next sequence value[SQL: select nextval ('user_id_seq')]
 ---> Npgsql.PostgresException (0x80004005): 42P01: relation "user_id_seq" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Id.SequenceGenerator.Generate(ISessionImplementor session, Object obj)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "user_id_seq" does not exist
    Position: 17
    File: d:\pginstaller_13.auto\postgres.windows-x64\src\backend\catalog\namespace.c
    Line: 434
    Routine: RangeVarGetRelidExtended
   --- End of inner exception stack trace ---
   at NHibernate.Id.SequenceGenerator.Generate(ISessionImplementor session, Object obj)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveEventListener.PerformSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSave(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.Save(Object obj)
   at Alduin.TestDatabaseCreator.Data.TestData.InsertEntity(IEntity entity)
   at Alduin.TestDatabaseCreator.Data.TestData.CreateUsers(String user, String email)
   at Alduin.TestDataBaseCreator.Program.CreateData(ISession session)
   at Alduin.TestDataBaseCreator.Program.Init()
