### ISSUE TITLE
Unable to create database.

### ISSUE THREAD

**Issue by urgheuigrpauipeg** [mogyiii/Alduin-botnet#4]
1. I installed Python lastest and PostgreSQL lastest
2. I deleted "ConnectDataBase" from appsettings.json and copyied the file to the panel folder
3. When i run Database creator I get this error, 

Recreating database...
Error:
Npgsql.PostgresException (0x80004005): 28P01: password authentication failed for user "postgres"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.AuthenticateSASL(List`1 mechanisms, String username, Boolean async)
   at Npgsql.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection()
   at NHibernate.Tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.Prepare()
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.GetReservedWords(Dialect dialect, IConnectionHelper connectionHelper)
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.UpdateDialectKeywords(Dialect dialect, IConnectionHelper connectionHelper)
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.Update(ISessionFactoryImplementor sessionFactory)
   at NHibernate.Impl.SessionFactoryImpl..ctor(Configuration cfg, IMapping mapping, Settings settings, EventListeners listeners)
   at NHibernate.Cfg.Configuration.BuildSessionFactory()
   at Alduin.TestDataBaseCreator.Program.Init()
  Exception data:
    Severity: FATAL
    SqlState: 28P01
    MessageText: password authentication failed for user "postgres"

**Comment by explowz** [comment]
Last line says it all.

**Comment by urgheuigrpauipeg** [comment]
> 
> 
> Last line says it all.

Thing is that I never changed the password, so I am a bit confused as to why it is not working.

**Comment by mogyiii** [comment]
Change password in appsettings.json to what you specified during installation. 
It is important that you do not enter the pgAdmin password, but the database password.
I forgot to enter it in the installation instructions.

**Comment by urgheuigrpauipeg** [comment]
> 
> 
> Change password in appsettings.json to what you specified during installation.
> It is important that you do not enter the pgAdmin password, but the database password.
> I forgot to enter it in the installation instructions.

Thanks so much, i forgot about that lol
