### ISSUE TITLE
Error attempting to create database.

### ISSUE THREAD

**Issue by urgheuigrpauipeg** [mogyiii/Alduin-botnet#6]
I have created a server in PostgresSQL called alduin and a database in it also called alduin. The super user is postgres and the password is admin. I however when running createdatabase get this error after entering the email...

NHibernate.Exceptions.GenericADOException: could not get next sequence value[SQL: select nextval ('user_id_seq')]
 ---> Npgsql.PostgresException (0x80004005): 42P01: relation "user_id_seq" does not exist
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(DbCommand cmd)
   at NHibernate.Id.SequenceGenerator.Generate(ISessionImplementor session, Object obj)
  Exception data:
    Severity: ERROR
    SqlState: 42P01
    MessageText: relation "user_id_seq" does not exist
    Position: 17
    File: d:\pginstaller_13.auto\postgres.windows-x64\src\backend\catalog\namespace.c
    Line: 434
    Routine: RangeVarGetRelidExtended
   --- End of inner exception stack trace ---
   at NHibernate.Id.SequenceGenerator.Generate(ISessionImplementor session, Object obj)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveEventListener.PerformSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSave(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.Save(Object obj)
   at Alduin.TestDatabaseCreator.Data.TestData.InsertEntity(IEntity entity)
   at Alduin.TestDatabaseCreator.Data.TestData.CreateUsers(String user, String email)
   at Alduin.TestDataBaseCreator.Program.CreateData(ISession session)
   at Alduin.TestDataBaseCreator.Program.Init()

**Comment by urgheuigrpauipeg** [comment]
fixed by dev on discord. import to alduin database or copy content to pgadmin querytool


import this: 

create table bot (id  serial, user_name varchar(255), key_unique varchar(255), key_certified varchar(255), country_code varchar(255), domain varchar(255), city varchar(255), last_ipaddress varchar(255), last_logged_in_utc timestamp, creation_date_utc timestamp, modification_date_utc timestamp, primary key (id));
create table bot_info (id  serial, hardware_name varchar(255), hardware_type varchar(255), performance varchar(255), other_information varchar(255), creation_date_utc timestamp, modification_date_utc timestamp, bot_id int4, primary key (id));
create table bot_log (id  serial, message varchar(255), type varchar(255), creation_date_utc timestamp, modification_date_utc timestamp, bot_id int4, primary key (id));
create table invitation (id  serial, invitation_key varchar(255), used boolean, creation_date_utc timestamp, modification_date_utc timestamp, user_id int4, primary key (id));
create table user_claim (id  serial, claim_type varchar(255), claim_value varchar(255), creation_date_utc timestamp, modification_date_utc timestamp, user_id int4, primary key (id));
create table "user" (id  serial, name varchar(255), user_name varchar(255), normalized_user_name varchar(255), password_hash varchar(255), email varchar(255), last_attempt_utc timestamp, access_failed_count int4, last_logged_in_utc timestamp, is_last_login_persistent boolean, security_stamp varchar(255), lockout_enabled boolean, lockout_end timestamp, is_deleted boolean, deletion_date_utc timestamp, creation_date_utc timestamp, modification_date_utc timestamp, primary key (id));
create index ix_bot_info_bot_id on bot_info (bot_id);
alter table bot_info add constraint fk_bot_bot_info foreign key (bot_id) references bot;
create index ix_bot_log_bot_id on bot_log (bot_id);
alter table bot_log add constraint fk_bot_bot_log foreign key (bot_id) references bot;
create index ix_invitation_user_id on invitation (user_id);
alter table invitation add constraint fk_user_invitation foreign key (user_id) references "user";
create index ix_user_claim_user_id on user_claim (user_id);
alter table user_claim add constraint fk_user_user_claim foreign key (user_id) references "user";
