### ISSUE TITLE
Some Tor errors

### ISSUE THREAD

**Issue by explowz** [mogyiii/Alduin-botnet#7]
In the Tor console log the line at which it stops is:
Tor error: System.ComponentModel.Win32Exception (5): Access is denied at System.Diagnostics.Process.Kill() at Alduin.Server.Modules.ConfigTor.KillTor()

Running Alduin.Stump.exe also stops at «Webmaster connection...»

Any dependencies I'm missing?

**Comment by mogyiii** [comment]
This "KillTor()" shutdown Tor process. try run  Alduin.web to administrator

**Comment by explowz** [comment]
2021. Jan 23 18:58:53.000 [notice] Bootstrapped 0% (starting): Starting
2021. Tor error: System.ComponentModel.Win32Exception (5): Access is denied at System.Diagnostics.Process.Kill() at Alduin.Server.Modules.ConfigTor.KillTor()
2021. Tor error: System.ComponentModel.Win32Exception (5): Access is denied at System.Diagnostics.Process.Kill() at Alduin.Server.Modules.ConfigTor.KillTor()

Nothing changed. Now it just writes it 2 times.

**Comment by explowz** [comment]
Should I have also ran DatabaseCreator as admin when I was setting it up?

**Comment by mogyiii** [comment]
no. Datebase creator just install db and datables and records user information. if database creator does not return an error then it does not need to be run multiple times. you can try running tor separately and disable tor in appsettings from alduin.web

**Comment by mogyiii** [comment]
or if you wait don't write something else? looking back at the code you shouldn't break the process

**Comment by explowz** [comment]
I haven't edited the torrc file at all. It seems to have done everything itself. Should I have changed something there?

**Comment by mogyiii** [comment]
try delete torrc file and run webpanel in principle, it generates a new one

**Comment by explowz** [comment]
OK

**Comment by explowz** [comment]
2021. Jan 26 14:53:27.551 [notice] Read configuration file "C:\Users\Administrator\Desktop\Alduin\Panel\Tor\Data\Tor\torrc".
2021. Jan 26 14:53:27.564 [warn] Failed to parse/validate config: Unknown option '∩╗┐ControlPort'. Failing.
2021. Jan 26 14:53:27.580 [err] Reading config failed--see warnings above.

**Comment by explowz** [comment]
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.IO.FileNotFoundException: Could not find file 'C:\Users\Administrator\Desktop\Alduin\Panel\Tor\Data\Tor\torrc'.
File name: 'C:\Users\Administrator\Desktop\Alduin\Panel\Tor\Data\Tor\torrc'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at Alduin.Web.Controllers.TorController.EditTorch()
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   
Errors in the Alduin.Web.exe

**Comment by explowz** [comment]
> try delete torrc file and run webpanel in principle, it generates a new one

Well... now it says (done) 100% but i still cant connect to the panel thru tor. i tried generating a new onion address but nothing happens. it just restarts tor

**Comment by explowz** [comment]
@mogyiii any solution or...?

**Comment by urgheuigrpauipeg** [comment]
Try installing the following SDK x86
https://dotnet.microsoft.com/download/dotnet-core/3.1
https://dotnet.microsoft.com/download/dotnet-core/2.1
https://dotnet.microsoft.com/download/dotnet-core/2.2

I personally don't remember what port to use to view it via tor but it think it is the same as local host (:5000) or (:44359)

**Comment by explowz** [comment]
Upon opening it on the port given :44359 it gives an error. SSL_ERROR_RX_RECORD_TOO_LONG

**Comment by explowz** [comment]
It worked, thank you. I only have 3 questions:
1. What's «KeyCertified» in settings?
2. What's «Run Tor for Website» in settings?
3. How do you create a stub?

**Comment by mogyiii** [comment]
sorry, for no reply. 
1. you don't have to change it, it's just a key that would have encrypted the message and connection, some parts are in it, but I still need to improve it to be good.
2. Run Tor for Alduin.Web together,
3. Navigate to stump open config.json and config it,  than create exe from stump folder

**Comment by explowz** [comment]
@mogyiii One quick question, why were HardBotKiller and Mutation removed?

**Comment by explowz** [comment]
Connection error: Starksoft.Aspen.Proxy.ProxyException: Connection to proxy host 127.0.0.1 on port 9150 failed. ---> Starksoft.Aspen.Proxy.ProxyException: proxy error: the connection was refused by the remote network for destination host kcpyvdbrq26x5h4w7zbnlql2oj44ez3tm36zrvx4bseqqejeqsoxukad.onion port number 5000.  Server response (hex): 050500010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.
   at Starksoft.Aspen.Proxy.Socks5ProxyClient.HandleProxyCommandError(Byte[] response, String destinationHost, Int32 destinationPort)
   at Starksoft.Aspen.Proxy.Socks5ProxyClient.SendCommand(Byte command, String destinationHost, Int32 destinationPort)
   at Starksoft.Aspen.Proxy.Socks5ProxyClient.CreateConnection(String destinationHost, Int32 destinationPort)
   --- End of inner exception stack trace ---
   at Starksoft.Aspen.Proxy.Socks5ProxyClient.CreateConnection(String destinationHost, Int32 destinationPort)
   at Alduin.Stump.SendHTTPonTor.TalkChannelHTTP(Object msg, String att, String address, Int32 ServerReachPort)
   
   I cannot create a stub due to this error

**Comment by mogyiii** [comment]
Do the "web" and "bot" run on the same machine?

**Comment by explowz** [comment]
Yes

**Comment by mogyiii** [comment]
The trouble. it will not work on the same machine because 2 tor cannot run on 1 machine

**Comment by explowz** [comment]
Ohh. OK

**Comment by explowz** [comment]
Do I also have to install PostgreSQL on the other machine?

**Comment by mogyiii** [comment]
no, just copy stump folder

**Comment by explowz** [comment]
Nothing happens when I run Alduin.Stump.exe with debug set to false. If I set to to true then it works. Without it I just get this error:
![cbf79543c9592e3636ece3994c1ed5c5](https://user-images.githubusercontent.com/20655963/106457603-e3d29480-6497-11eb-83a0-4a19a53194b9.png)

**Comment by mogyiii** [comment]
can you send me yours config.js?

**Comment by explowz** [comment]
You mean Config.json?

**Comment by explowz** [comment]
Added you on Discord.
